import "./App.css";

function App() {
  return (
    <>
      <div className="blackcolordiv">
        <img
          className="cat1"
          src="https://www.svgrepo.com/show/481273/cat-2.svg"
          alt=""
        />
        <img
          className="cat2"
          src="https://www.svgrepo.com/show/481273/cat-2.svg"
          alt=""
        />
        <img
          className="cat3"
          src="https://www.svgrepo.com/show/481273/cat-2.svg"
          alt=""
        />
        <img
          className="cat4"
          src="https://www.svgrepo.com/show/481273/cat-2.svg"
          alt=""
        />
        <img
          className="cat5"
          src="https://www.svgrepo.com/show/481273/cat-2.svg"
          alt=""
        />
        <img
          className="cat6"
          src="https://www.svgrepo.com/show/481273/cat-2.svg"
          alt=""
        />
        <img
          className="cat7"
          src="https://www.svgrepo.com/show/481273/cat-2.svg"
          alt=""
        />
        <img
          className="cat8"
          src="https://www.svgrepo.com/show/481273/cat-2.svg"
          alt=""
        />
        <img
          className="cat9"
          src="https://www.svgrepo.com/show/481273/cat-2.svg"
          alt=""
        />
        <img
          className="cat10"
          src="https://www.svgrepo.com/show/481273/cat-2.svg"
          alt=""
        />
        <img
          className="cat11"
          src="https://www.svgrepo.com/show/481273/cat-2.svg"
          alt=""
        />
        <img
          className="cat12"
          src="https://www.svgrepo.com/show/481273/cat-2.svg"
          alt=""
        />
        <img
          className="cat13"
          src="https://www.svgrepo.com/show/481273/cat-2.svg"
          alt=""
        />
        <img
          className="cat14"
          src="https://www.svgrepo.com/show/481273/cat-2.svg"
          alt=""
        />
        <img
          className="cat15"
          src="https://www.svgrepo.com/show/481273/cat-2.svg"
          alt=""
        />
        <img
          className="cat16"
          src="https://www.svgrepo.com/show/481273/cat-2.svg"
          alt=""
        />
        <img
          className="cat17"
          src="https://www.svgrepo.com/show/481273/cat-2.svg"
          alt=""
        />
        <img
          className="cat18"
          src="https://www.svgrepo.com/show/481273/cat-2.svg"
          alt=""
        />
        <img
          className="cat19"
          src="https://www.svgrepo.com/show/481273/cat-2.svg"
          alt=""
        />
        <img
          className="cat20"
          src="https://www.svgrepo.com/show/481273/cat-2.svg"
          alt=""
        />
        <img
          className="cat21"
          src="https://www.svgrepo.com/show/481273/cat-2.svg"
          alt=""
        />
        <img
          className="cat22"
          src="https://www.svgrepo.com/show/481273/cat-2.svg"
          alt=""
        />
        <img
          className="cat23"
          src="https://www.svgrepo.com/show/481273/cat-2.svg"
          alt=""
        />
        <img
          className="cat24"
          src="https://www.svgrepo.com/show/481273/cat-2.svg"
          alt=""
        />
        <img
          className="cat25"
          src="https://www.svgrepo.com/show/481273/cat-2.svg"
          alt=""
        />
        <img
          className="cat26"
          src="https://www.svgrepo.com/show/481273/cat-2.svg"
          alt=""
        />
        <img
          className="cat27"
          src="https://www.svgrepo.com/show/481273/cat-2.svg"
          alt=""
        />
        <img
          className="cat28"
          src="https://www.svgrepo.com/show/481273/cat-2.svg"
          alt=""
        />
        <img
          className="cat29"
          src="https://www.svgrepo.com/show/481273/cat-2.svg"
          alt=""
        />
        <img
          className="cat30"
          src="https://www.svgrepo.com/show/481273/cat-2.svg"
          alt=""
        />
        <img
          className="cat31"
          src="https://www.svgrepo.com/show/481273/cat-2.svg"
          alt=""
        />
        <div className="headerdiv">
          <h1 className="fontdif">I'm Alexis Tobias, </h1>
          <h1 className="fontdif2">Front-End</h1>
          <a href="">
            <img
              className="github"
              src="https://www.svgrepo.com/show/512317/github-142.svg"
              alt=""
            />
          </a>
          <div>
            <p className="fontdifp">
              Love petting cats 😸, working out at the gym 🏋🏻‍♀️ and learning new
              things to code. From Mexico 🌮
            </p>
          </div>
        </div>
      </div>
    </>
  );
}

export default App;
